### ISSUE TITLE
Doesn't seem to work with Blender 3.6.2

### ISSUE THREAD

**Issue by Ryanscastle** [negdo/SaveSelection#7]
I know the description doesn't list this newest version but I was hoping it would work.
The context menu has save and restore selection options now. The scene selection adds items.
The restore selection button doesn't restore the selection though.

**Comment by negdo** [comment]
I tested the addon again on the Blender 3.6.2, it still seems to work normaly for me. Can you provide more details about your system? Also, can you check if Blender's system console is outputing any errors?

**Comment by Ryanscastle** [comment]
I opened a new document and it works on the cube that shows up at the beginning. It doesn't work on the large file I'm working on. I'm not a blender expert. I'm a self taught noob, however I did figure out how to see system console errors. This error occurs when I click a face to select it:
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0
Traceback (most recent call last):
  File "C:\Users\ryans\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SaveSelection-main\save_selection.py", line 270, in poll
    if context.scene.saved_selections[context.scene.save_selection_index] is None:
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0
Traceback (most recent call last):
  File "C:\Users\ryans\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SaveSelection-main\save_selection.py", line 270, in poll
    if context.scene.saved_selections[context.scene.save_selection_index] is None:

There must be something different with the scene or file or something that makes it not work.

**Comment by negdo** [comment]
I was able to find and fix some bugs related to the error you showed me. Please try downloading the new version and tell me, if it also fixed your original problem.

**Comment by Ryanscastle** [comment]
Now there are no errors showing up in system console.
What happens is that I select faces and save and everything seems fine but when I go to restore selection it changes from edit mode to object mode and there is nothing selected.

**Comment by Ryanscastle** [comment]
I have tried several models including a previous version of the model I'm working on and it works. Perhaps my current model is corrupted?

**Comment by Ryanscastle** [comment]
another update,
I had it working and then I got this:

Traceback (most recent call last):
  File "C:\Users\ryans\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SaveSelection-main\save_selection.py", line 170, in execute
    return {"FINISHED"}
IndexError: bpy_prop_collection[index]: index 4 out of range, size 1
Error: Python: Traceback (most recent call last):
  File "C:\Users\ryans\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SaveSelection-main\save_selection.py", line 170, in execute
    return {"FINISHED"}
IndexError: bpy_prop_collection[index]: index 4 out of range, size 1
